name: build

on:
  push:

jobs:
  # Referring to https://github.com/sharkdp/bat/blob/master/.github/workflows/CICD.yml
  build-on-mac:
    name: aarch64-apple-darwin (macos-12)
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        job:
          - target: aarch64-apple-darwin
          - target: x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v3
      - run: brew install zig
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
      - run: rustup target add ${{ matrix.job.target }}
      - run: cargo install cargo-zigbuild
      - run: cargo zigbuild --release --target=${{ matrix.job.target }}
      - uses: actions/upload-artifact@v3
        with:
          name: binary-${{ matrix.job.target }}
          path: target/${{ matrix.job.target }}/release/kabeuchi

  build-on-ubuntu:
    name: ${{ matrix.job.target }} (ubuntu-22.04)
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        job:
          - target: aarch64-unknown-linux-gnu
          - target: arm-unknown-linux-gnueabihf
          - target: arm-unknown-linux-musleabihf
          - target: i686-unknown-linux-gnu
          - target: i686-unknown-linux-musl
          - target: x86_64-pc-windows-gnu
          - target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v3
      - name: Install prerequistites
        shell: bash
        run: |
          case ${{ matrix.job.target }} in
            arm-unknown-linux-*) sudo apt-get -y update ; sudo apt-get -y install gcc-arm-linux-gnueabihf ;;
            aarch64-unknown-linux-gnu) sudo apt-get -y update ; sudo apt-get -y install gcc-aarch64-linux-gnu ;;
          esac
      - run: sudo snap install zig --classic --beta
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add ${{ matrix.job.target }}
      - run: cargo install cargo-zigbuild
      - run: cargo zigbuild --release --target=${{ matrix.job.target }}
      - uses: actions/upload-artifact@v3
        with:
          name: binary-${{ matrix.job.target }}
          path: target/${{ matrix.job.target }}/release/kabeuchi

  build-on-windows:
    name: ${{ matrix.job.target }} (windows-2022)
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        job:
          - target: i686-pc-windows-msvc
          - target: x86_64-pc-windows-gnu
          - target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.job.target }}
      - run: cargo build --release --target=${{ matrix.job.target }}
      - uses: actions/upload-artifact@v3
        with:
          name: binary-${{ matrix.job.target }}
          path: target/${{ matrix.job.target }}/release/kabeuchi.exe